export const SET_JOGS = 'SET_JOGS';
export const JOGS_BY_DATES = 'JOGS_BY_DATES';
export const CHANGE_FILTER_VISIBLE = 'CHANGE_FILTER_VISIBLE';
export const CHANGE_IS_FETCHING_STATUS = 'CHANGE_IS_FETCHING_STATUS';